trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

jobs:
  - job:
    displayName: manylinux
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: "Install rust"

      - bash: |
          cargo install maturin
        displayName: "Install maturin"

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'

      - script: |
          python -m pip install --upgrade pip setuptools wheel
        displayName: 'Update pip'

      - script: |
          maturin build -o $(Build.BinariesDirectory)
        workingDirectory: "$(Build.SourcesDirectory)/examples/path_or_file_like"
        displayName: 'maturin build'

      - script: |
          pip install $(Build.BinariesDirectory)/path_or_file_like-*-cp36-*.whl
        displayName: 'Install new wheel'

      - script: |
          pip install pytest pytest-azurepipelines
          pytest
        workingDirectory: "$(Build.SourcesDirectory)/examples/path_or_file_like"
        displayName: 'pytest'


  - job:
    displayName: macOS-10.13

    pool:
      vmImage: 'macOS-10.13'

    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: "Install rust"

      - bash: |
          cargo install maturin
        displayName: "Install maturin"

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'

      - script: |
          python -m pip install --upgrade pip setuptools wheel
        displayName: 'Update Pip'

      - script: |
          maturin build -o $(Build.BinariesDirectory)
        workingDirectory: "$(Build.SourcesDirectory)/examples/path_or_file_like"
        displayName: 'maturin build'

      - script: |
          pip install $(Build.BinariesDirectory)/path_or_file_like-*-cp36-*.whl
        displayName: 'Install new wheel'

      - script: |
          pip install pytest pytest-azurepipelines
          pytest
        workingDirectory: "$(Build.SourcesDirectory)/examples/path_or_file_like"
        displayName: 'pytest'


  - job:
    displayName: Windows

    pool:
      vmImage: 'vs2017-win2016'

    steps:
      - script: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -y --default-toolchain nightly
          echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
        displayName: Install rust

      - script: |
          cargo install maturin
        displayName: "Install maturin"

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          architecture: 'x64'

      - script: |
          python -m pip install --upgrade pip setuptools wheel
        displayName: 'Install maturin'

      - script: |
          maturin build -o $(Build.BinariesDirectory)
        workingDirectory: "$(Build.SourcesDirectory)/examples/path_or_file_like"
        displayName: 'maturin build'

      - powershell: |
          pip install $(Build.BinariesDirectory)/$(Get-ChildItem $(Build.BinariesDirectory)/path_or_file_like-*-cp36-*.whl | Select -exp Name)
        displayName: 'Install new wheel'

      - script: |
          pip install pytest pytest-azurepipelines
          pytest
        workingDirectory: "$(Build.SourcesDirectory)/examples/path_or_file_like"
        displayName: 'pytest'